server:
  port: 8081

spring:
  application:
    name: Clever IT Challenge
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/clever?currentSchema=public&ssl=false
    username: postgres
    password: admin12345
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 5
    elementSize: 10
